################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow/tensorflow/core/framework/allocator_test.cc \
../tensorflow/tensorflow/core/framework/attr_value_util.cc \
../tensorflow/tensorflow/core/framework/attr_value_util_test.cc \
../tensorflow/tensorflow/core/framework/batch_util_test.cc \
../tensorflow/tensorflow/core/framework/bfloat16.cc \
../tensorflow/tensorflow/core/framework/bfloat16_test.cc \
../tensorflow/tensorflow/core/framework/collective.cc \
../tensorflow/tensorflow/core/framework/common_shape_fns.cc \
../tensorflow/tensorflow/core/framework/common_shape_fns_test.cc \
../tensorflow/tensorflow/core/framework/dataset.cc \
../tensorflow/tensorflow/core/framework/dataset_test.cc \
../tensorflow/tensorflow/core/framework/device.cc \
../tensorflow/tensorflow/core/framework/device_base.cc \
../tensorflow/tensorflow/core/framework/device_base_test.cc \
../tensorflow/tensorflow/core/framework/device_factory.cc \
../tensorflow/tensorflow/core/framework/disable_jit_test.cc \
../tensorflow/tensorflow/core/framework/fake_input.cc \
../tensorflow/tensorflow/core/framework/full_type_inference_util.cc \
../tensorflow/tensorflow/core/framework/full_type_inference_util_test.cc \
../tensorflow/tensorflow/core/framework/full_type_util.cc \
../tensorflow/tensorflow/core/framework/full_type_util_test.cc \
../tensorflow/tensorflow/core/framework/function.cc \
../tensorflow/tensorflow/core/framework/function_handle_cache.cc \
../tensorflow/tensorflow/core/framework/function_test.cc \
../tensorflow/tensorflow/core/framework/function_testlib.cc \
../tensorflow/tensorflow/core/framework/graph_def_util.cc \
../tensorflow/tensorflow/core/framework/graph_def_util_test.cc \
../tensorflow/tensorflow/core/framework/graph_to_functiondef.cc \
../tensorflow/tensorflow/core/framework/graph_to_functiondef_test.cc \
../tensorflow/tensorflow/core/framework/kernel_def_builder.cc \
../tensorflow/tensorflow/core/framework/kernel_def_builder_test.cc \
../tensorflow/tensorflow/core/framework/kernel_def_util.cc \
../tensorflow/tensorflow/core/framework/kernel_def_util_test.cc \
../tensorflow/tensorflow/core/framework/kernel_shape_util.cc \
../tensorflow/tensorflow/core/framework/load_library.cc \
../tensorflow/tensorflow/core/framework/local_rendezvous.cc \
../tensorflow/tensorflow/core/framework/log_memory.cc \
../tensorflow/tensorflow/core/framework/logging.cc \
../tensorflow/tensorflow/core/framework/lookup_interface.cc \
../tensorflow/tensorflow/core/framework/memory_types.cc \
../tensorflow/tensorflow/core/framework/memory_types_test.cc \
../tensorflow/tensorflow/core/framework/metrics.cc \
../tensorflow/tensorflow/core/framework/model.cc \
../tensorflow/tensorflow/core/framework/model_test.cc \
../tensorflow/tensorflow/core/framework/node_def_builder.cc \
../tensorflow/tensorflow/core/framework/node_def_builder_test.cc \
../tensorflow/tensorflow/core/framework/node_def_util.cc \
../tensorflow/tensorflow/core/framework/node_def_util_test.cc \
../tensorflow/tensorflow/core/framework/node_properties.cc \
../tensorflow/tensorflow/core/framework/node_properties_test.cc \
../tensorflow/tensorflow/core/framework/op.cc \
../tensorflow/tensorflow/core/framework/op_compatibility_test.cc \
../tensorflow/tensorflow/core/framework/op_def_builder.cc \
../tensorflow/tensorflow/core/framework/op_def_builder_test.cc \
../tensorflow/tensorflow/core/framework/op_def_util.cc \
../tensorflow/tensorflow/core/framework/op_def_util_test.cc \
../tensorflow/tensorflow/core/framework/op_gen_lib.cc \
../tensorflow/tensorflow/core/framework/op_gen_lib_test.cc \
../tensorflow/tensorflow/core/framework/op_kernel.cc \
../tensorflow/tensorflow/core/framework/op_kernel_test.cc \
../tensorflow/tensorflow/core/framework/op_registration_test.cc \
../tensorflow/tensorflow/core/framework/op_segment.cc \
../tensorflow/tensorflow/core/framework/op_segment_test.cc \
../tensorflow/tensorflow/core/framework/ops_util.cc \
../tensorflow/tensorflow/core/framework/partial_tensor_shape_test.cc \
../tensorflow/tensorflow/core/framework/reader_base.cc \
../tensorflow/tensorflow/core/framework/ref_var.cc \
../tensorflow/tensorflow/core/framework/rendezvous.cc \
../tensorflow/tensorflow/core/framework/rendezvous_test.cc \
../tensorflow/tensorflow/core/framework/resource_handle.cc \
../tensorflow/tensorflow/core/framework/resource_handle_test.cc \
../tensorflow/tensorflow/core/framework/resource_mgr.cc \
../tensorflow/tensorflow/core/framework/resource_mgr_test.cc \
../tensorflow/tensorflow/core/framework/resource_op_kernel_test.cc \
../tensorflow/tensorflow/core/framework/resource_var.cc \
../tensorflow/tensorflow/core/framework/resource_var_test.cc \
../tensorflow/tensorflow/core/framework/run_handler.cc \
../tensorflow/tensorflow/core/framework/run_handler_test.cc \
../tensorflow/tensorflow/core/framework/run_handler_util.cc \
../tensorflow/tensorflow/core/framework/run_handler_util_test.cc \
../tensorflow/tensorflow/core/framework/shape_inference.cc \
../tensorflow/tensorflow/core/framework/shape_inference_test.cc \
../tensorflow/tensorflow/core/framework/shape_inference_testutil.cc \
../tensorflow/tensorflow/core/framework/shape_inference_testutil_test.cc \
../tensorflow/tensorflow/core/framework/tensor.cc \
../tensorflow/tensorflow/core/framework/tensor_fuzz.cc \
../tensorflow/tensorflow/core/framework/tensor_shape.cc \
../tensorflow/tensorflow/core/framework/tensor_shape_fuzz.cc \
../tensorflow/tensorflow/core/framework/tensor_shape_test.cc \
../tensorflow/tensorflow/core/framework/tensor_slice.cc \
../tensorflow/tensorflow/core/framework/tensor_slice_test.cc \
../tensorflow/tensorflow/core/framework/tensor_test.cc \
../tensorflow/tensorflow/core/framework/tensor_testutil.cc \
../tensorflow/tensorflow/core/framework/tensor_testutil_test.cc \
../tensorflow/tensorflow/core/framework/tensor_util.cc \
../tensorflow/tensorflow/core/framework/tensor_util_test.cc \
../tensorflow/tensorflow/core/framework/tracking_allocator_test.cc \
../tensorflow/tensorflow/core/framework/typed_allocator.cc \
../tensorflow/tensorflow/core/framework/types.cc \
../tensorflow/tensorflow/core/framework/types_test.cc \
../tensorflow/tensorflow/core/framework/variant.cc \
../tensorflow/tensorflow/core/framework/variant_op_copy_test.cc \
../tensorflow/tensorflow/core/framework/variant_op_registry.cc \
../tensorflow/tensorflow/core/framework/variant_op_registry_test.cc \
../tensorflow/tensorflow/core/framework/variant_tensor_data.cc \
../tensorflow/tensorflow/core/framework/variant_test.cc \
../tensorflow/tensorflow/core/framework/versions.cc 

CC_DEPS += \
./tensorflow/tensorflow/core/framework/allocator_test.d \
./tensorflow/tensorflow/core/framework/attr_value_util.d \
./tensorflow/tensorflow/core/framework/attr_value_util_test.d \
./tensorflow/tensorflow/core/framework/batch_util_test.d \
./tensorflow/tensorflow/core/framework/bfloat16.d \
./tensorflow/tensorflow/core/framework/bfloat16_test.d \
./tensorflow/tensorflow/core/framework/collective.d \
./tensorflow/tensorflow/core/framework/common_shape_fns.d \
./tensorflow/tensorflow/core/framework/common_shape_fns_test.d \
./tensorflow/tensorflow/core/framework/dataset.d \
./tensorflow/tensorflow/core/framework/dataset_test.d \
./tensorflow/tensorflow/core/framework/device.d \
./tensorflow/tensorflow/core/framework/device_base.d \
./tensorflow/tensorflow/core/framework/device_base_test.d \
./tensorflow/tensorflow/core/framework/device_factory.d \
./tensorflow/tensorflow/core/framework/disable_jit_test.d \
./tensorflow/tensorflow/core/framework/fake_input.d \
./tensorflow/tensorflow/core/framework/full_type_inference_util.d \
./tensorflow/tensorflow/core/framework/full_type_inference_util_test.d \
./tensorflow/tensorflow/core/framework/full_type_util.d \
./tensorflow/tensorflow/core/framework/full_type_util_test.d \
./tensorflow/tensorflow/core/framework/function.d \
./tensorflow/tensorflow/core/framework/function_handle_cache.d \
./tensorflow/tensorflow/core/framework/function_test.d \
./tensorflow/tensorflow/core/framework/function_testlib.d \
./tensorflow/tensorflow/core/framework/graph_def_util.d \
./tensorflow/tensorflow/core/framework/graph_def_util_test.d \
./tensorflow/tensorflow/core/framework/graph_to_functiondef.d \
./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.d \
./tensorflow/tensorflow/core/framework/kernel_def_builder.d \
./tensorflow/tensorflow/core/framework/kernel_def_builder_test.d \
./tensorflow/tensorflow/core/framework/kernel_def_util.d \
./tensorflow/tensorflow/core/framework/kernel_def_util_test.d \
./tensorflow/tensorflow/core/framework/kernel_shape_util.d \
./tensorflow/tensorflow/core/framework/load_library.d \
./tensorflow/tensorflow/core/framework/local_rendezvous.d \
./tensorflow/tensorflow/core/framework/log_memory.d \
./tensorflow/tensorflow/core/framework/logging.d \
./tensorflow/tensorflow/core/framework/lookup_interface.d \
./tensorflow/tensorflow/core/framework/memory_types.d \
./tensorflow/tensorflow/core/framework/memory_types_test.d \
./tensorflow/tensorflow/core/framework/metrics.d \
./tensorflow/tensorflow/core/framework/model.d \
./tensorflow/tensorflow/core/framework/model_test.d \
./tensorflow/tensorflow/core/framework/node_def_builder.d \
./tensorflow/tensorflow/core/framework/node_def_builder_test.d \
./tensorflow/tensorflow/core/framework/node_def_util.d \
./tensorflow/tensorflow/core/framework/node_def_util_test.d \
./tensorflow/tensorflow/core/framework/node_properties.d \
./tensorflow/tensorflow/core/framework/node_properties_test.d \
./tensorflow/tensorflow/core/framework/op.d \
./tensorflow/tensorflow/core/framework/op_compatibility_test.d \
./tensorflow/tensorflow/core/framework/op_def_builder.d \
./tensorflow/tensorflow/core/framework/op_def_builder_test.d \
./tensorflow/tensorflow/core/framework/op_def_util.d \
./tensorflow/tensorflow/core/framework/op_def_util_test.d \
./tensorflow/tensorflow/core/framework/op_gen_lib.d \
./tensorflow/tensorflow/core/framework/op_gen_lib_test.d \
./tensorflow/tensorflow/core/framework/op_kernel.d \
./tensorflow/tensorflow/core/framework/op_kernel_test.d \
./tensorflow/tensorflow/core/framework/op_registration_test.d \
./tensorflow/tensorflow/core/framework/op_segment.d \
./tensorflow/tensorflow/core/framework/op_segment_test.d \
./tensorflow/tensorflow/core/framework/ops_util.d \
./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.d \
./tensorflow/tensorflow/core/framework/reader_base.d \
./tensorflow/tensorflow/core/framework/ref_var.d \
./tensorflow/tensorflow/core/framework/rendezvous.d \
./tensorflow/tensorflow/core/framework/rendezvous_test.d \
./tensorflow/tensorflow/core/framework/resource_handle.d \
./tensorflow/tensorflow/core/framework/resource_handle_test.d \
./tensorflow/tensorflow/core/framework/resource_mgr.d \
./tensorflow/tensorflow/core/framework/resource_mgr_test.d \
./tensorflow/tensorflow/core/framework/resource_op_kernel_test.d \
./tensorflow/tensorflow/core/framework/resource_var.d \
./tensorflow/tensorflow/core/framework/resource_var_test.d \
./tensorflow/tensorflow/core/framework/run_handler.d \
./tensorflow/tensorflow/core/framework/run_handler_test.d \
./tensorflow/tensorflow/core/framework/run_handler_util.d \
./tensorflow/tensorflow/core/framework/run_handler_util_test.d \
./tensorflow/tensorflow/core/framework/shape_inference.d \
./tensorflow/tensorflow/core/framework/shape_inference_test.d \
./tensorflow/tensorflow/core/framework/shape_inference_testutil.d \
./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.d \
./tensorflow/tensorflow/core/framework/tensor.d \
./tensorflow/tensorflow/core/framework/tensor_fuzz.d \
./tensorflow/tensorflow/core/framework/tensor_shape.d \
./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.d \
./tensorflow/tensorflow/core/framework/tensor_shape_test.d \
./tensorflow/tensorflow/core/framework/tensor_slice.d \
./tensorflow/tensorflow/core/framework/tensor_slice_test.d \
./tensorflow/tensorflow/core/framework/tensor_test.d \
./tensorflow/tensorflow/core/framework/tensor_testutil.d \
./tensorflow/tensorflow/core/framework/tensor_testutil_test.d \
./tensorflow/tensorflow/core/framework/tensor_util.d \
./tensorflow/tensorflow/core/framework/tensor_util_test.d \
./tensorflow/tensorflow/core/framework/tracking_allocator_test.d \
./tensorflow/tensorflow/core/framework/typed_allocator.d \
./tensorflow/tensorflow/core/framework/types.d \
./tensorflow/tensorflow/core/framework/types_test.d \
./tensorflow/tensorflow/core/framework/variant.d \
./tensorflow/tensorflow/core/framework/variant_op_copy_test.d \
./tensorflow/tensorflow/core/framework/variant_op_registry.d \
./tensorflow/tensorflow/core/framework/variant_op_registry_test.d \
./tensorflow/tensorflow/core/framework/variant_tensor_data.d \
./tensorflow/tensorflow/core/framework/variant_test.d \
./tensorflow/tensorflow/core/framework/versions.d 

OBJS += \
./tensorflow/tensorflow/core/framework/allocator_test.o \
./tensorflow/tensorflow/core/framework/attr_value_util.o \
./tensorflow/tensorflow/core/framework/attr_value_util_test.o \
./tensorflow/tensorflow/core/framework/batch_util_test.o \
./tensorflow/tensorflow/core/framework/bfloat16.o \
./tensorflow/tensorflow/core/framework/bfloat16_test.o \
./tensorflow/tensorflow/core/framework/collective.o \
./tensorflow/tensorflow/core/framework/common_shape_fns.o \
./tensorflow/tensorflow/core/framework/common_shape_fns_test.o \
./tensorflow/tensorflow/core/framework/dataset.o \
./tensorflow/tensorflow/core/framework/dataset_test.o \
./tensorflow/tensorflow/core/framework/device.o \
./tensorflow/tensorflow/core/framework/device_base.o \
./tensorflow/tensorflow/core/framework/device_base_test.o \
./tensorflow/tensorflow/core/framework/device_factory.o \
./tensorflow/tensorflow/core/framework/disable_jit_test.o \
./tensorflow/tensorflow/core/framework/fake_input.o \
./tensorflow/tensorflow/core/framework/full_type_inference_util.o \
./tensorflow/tensorflow/core/framework/full_type_inference_util_test.o \
./tensorflow/tensorflow/core/framework/full_type_util.o \
./tensorflow/tensorflow/core/framework/full_type_util_test.o \
./tensorflow/tensorflow/core/framework/function.o \
./tensorflow/tensorflow/core/framework/function_handle_cache.o \
./tensorflow/tensorflow/core/framework/function_test.o \
./tensorflow/tensorflow/core/framework/function_testlib.o \
./tensorflow/tensorflow/core/framework/graph_def_util.o \
./tensorflow/tensorflow/core/framework/graph_def_util_test.o \
./tensorflow/tensorflow/core/framework/graph_to_functiondef.o \
./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.o \
./tensorflow/tensorflow/core/framework/kernel_def_builder.o \
./tensorflow/tensorflow/core/framework/kernel_def_builder_test.o \
./tensorflow/tensorflow/core/framework/kernel_def_util.o \
./tensorflow/tensorflow/core/framework/kernel_def_util_test.o \
./tensorflow/tensorflow/core/framework/kernel_shape_util.o \
./tensorflow/tensorflow/core/framework/load_library.o \
./tensorflow/tensorflow/core/framework/local_rendezvous.o \
./tensorflow/tensorflow/core/framework/log_memory.o \
./tensorflow/tensorflow/core/framework/logging.o \
./tensorflow/tensorflow/core/framework/lookup_interface.o \
./tensorflow/tensorflow/core/framework/memory_types.o \
./tensorflow/tensorflow/core/framework/memory_types_test.o \
./tensorflow/tensorflow/core/framework/metrics.o \
./tensorflow/tensorflow/core/framework/model.o \
./tensorflow/tensorflow/core/framework/model_test.o \
./tensorflow/tensorflow/core/framework/node_def_builder.o \
./tensorflow/tensorflow/core/framework/node_def_builder_test.o \
./tensorflow/tensorflow/core/framework/node_def_util.o \
./tensorflow/tensorflow/core/framework/node_def_util_test.o \
./tensorflow/tensorflow/core/framework/node_properties.o \
./tensorflow/tensorflow/core/framework/node_properties_test.o \
./tensorflow/tensorflow/core/framework/op.o \
./tensorflow/tensorflow/core/framework/op_compatibility_test.o \
./tensorflow/tensorflow/core/framework/op_def_builder.o \
./tensorflow/tensorflow/core/framework/op_def_builder_test.o \
./tensorflow/tensorflow/core/framework/op_def_util.o \
./tensorflow/tensorflow/core/framework/op_def_util_test.o \
./tensorflow/tensorflow/core/framework/op_gen_lib.o \
./tensorflow/tensorflow/core/framework/op_gen_lib_test.o \
./tensorflow/tensorflow/core/framework/op_kernel.o \
./tensorflow/tensorflow/core/framework/op_kernel_test.o \
./tensorflow/tensorflow/core/framework/op_registration_test.o \
./tensorflow/tensorflow/core/framework/op_segment.o \
./tensorflow/tensorflow/core/framework/op_segment_test.o \
./tensorflow/tensorflow/core/framework/ops_util.o \
./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.o \
./tensorflow/tensorflow/core/framework/reader_base.o \
./tensorflow/tensorflow/core/framework/ref_var.o \
./tensorflow/tensorflow/core/framework/rendezvous.o \
./tensorflow/tensorflow/core/framework/rendezvous_test.o \
./tensorflow/tensorflow/core/framework/resource_handle.o \
./tensorflow/tensorflow/core/framework/resource_handle_test.o \
./tensorflow/tensorflow/core/framework/resource_mgr.o \
./tensorflow/tensorflow/core/framework/resource_mgr_test.o \
./tensorflow/tensorflow/core/framework/resource_op_kernel_test.o \
./tensorflow/tensorflow/core/framework/resource_var.o \
./tensorflow/tensorflow/core/framework/resource_var_test.o \
./tensorflow/tensorflow/core/framework/run_handler.o \
./tensorflow/tensorflow/core/framework/run_handler_test.o \
./tensorflow/tensorflow/core/framework/run_handler_util.o \
./tensorflow/tensorflow/core/framework/run_handler_util_test.o \
./tensorflow/tensorflow/core/framework/shape_inference.o \
./tensorflow/tensorflow/core/framework/shape_inference_test.o \
./tensorflow/tensorflow/core/framework/shape_inference_testutil.o \
./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.o \
./tensorflow/tensorflow/core/framework/tensor.o \
./tensorflow/tensorflow/core/framework/tensor_fuzz.o \
./tensorflow/tensorflow/core/framework/tensor_shape.o \
./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.o \
./tensorflow/tensorflow/core/framework/tensor_shape_test.o \
./tensorflow/tensorflow/core/framework/tensor_slice.o \
./tensorflow/tensorflow/core/framework/tensor_slice_test.o \
./tensorflow/tensorflow/core/framework/tensor_test.o \
./tensorflow/tensorflow/core/framework/tensor_testutil.o \
./tensorflow/tensorflow/core/framework/tensor_testutil_test.o \
./tensorflow/tensorflow/core/framework/tensor_util.o \
./tensorflow/tensorflow/core/framework/tensor_util_test.o \
./tensorflow/tensorflow/core/framework/tracking_allocator_test.o \
./tensorflow/tensorflow/core/framework/typed_allocator.o \
./tensorflow/tensorflow/core/framework/types.o \
./tensorflow/tensorflow/core/framework/types_test.o \
./tensorflow/tensorflow/core/framework/variant.o \
./tensorflow/tensorflow/core/framework/variant_op_copy_test.o \
./tensorflow/tensorflow/core/framework/variant_op_registry.o \
./tensorflow/tensorflow/core/framework/variant_op_registry_test.o \
./tensorflow/tensorflow/core/framework/variant_tensor_data.o \
./tensorflow/tensorflow/core/framework/variant_test.o \
./tensorflow/tensorflow/core/framework/versions.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow/tensorflow/core/framework/%.o tensorflow/tensorflow/core/framework/%.su tensorflow/tensorflow/core/framework/%.cyclo: ../tensorflow/tensorflow/core/framework/%.cc tensorflow/tensorflow/core/framework/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m7 -std=gnu++17 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H747xx -DUSE_STM32H747I_DISCO -DCORE_CM7 -DSTM32IPL -DARM_MATH_CM7 -D__FPU_PRESENT=1 -c -I../Core/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Drivers/CMSIS/DSP/Include -I../Drivers/BSP/Components/Common -I../Drivers/BSP/STM32H747I-DISCO -I../Utilites/CPU -I../Utilites/Fonts -I../Utilites/lcd -I../tensorflow -I../Middlewares/ST/STM32_ImageProcessing_Library/Inc -I../third_party -I../third_party/flatbuffers/include -I../third_party/ruy -I../third_party/gemmlowp -I../Models -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-tensorflow-2f-tensorflow-2f-core-2f-framework

clean-tensorflow-2f-tensorflow-2f-core-2f-framework:
	-$(RM) ./tensorflow/tensorflow/core/framework/allocator_test.cyclo ./tensorflow/tensorflow/core/framework/allocator_test.d ./tensorflow/tensorflow/core/framework/allocator_test.o ./tensorflow/tensorflow/core/framework/allocator_test.su ./tensorflow/tensorflow/core/framework/attr_value_util.cyclo ./tensorflow/tensorflow/core/framework/attr_value_util.d ./tensorflow/tensorflow/core/framework/attr_value_util.o ./tensorflow/tensorflow/core/framework/attr_value_util.su ./tensorflow/tensorflow/core/framework/attr_value_util_test.cyclo ./tensorflow/tensorflow/core/framework/attr_value_util_test.d ./tensorflow/tensorflow/core/framework/attr_value_util_test.o ./tensorflow/tensorflow/core/framework/attr_value_util_test.su ./tensorflow/tensorflow/core/framework/batch_util_test.cyclo ./tensorflow/tensorflow/core/framework/batch_util_test.d ./tensorflow/tensorflow/core/framework/batch_util_test.o ./tensorflow/tensorflow/core/framework/batch_util_test.su ./tensorflow/tensorflow/core/framework/bfloat16.cyclo ./tensorflow/tensorflow/core/framework/bfloat16.d ./tensorflow/tensorflow/core/framework/bfloat16.o ./tensorflow/tensorflow/core/framework/bfloat16.su ./tensorflow/tensorflow/core/framework/bfloat16_test.cyclo ./tensorflow/tensorflow/core/framework/bfloat16_test.d ./tensorflow/tensorflow/core/framework/bfloat16_test.o ./tensorflow/tensorflow/core/framework/bfloat16_test.su ./tensorflow/tensorflow/core/framework/collective.cyclo ./tensorflow/tensorflow/core/framework/collective.d ./tensorflow/tensorflow/core/framework/collective.o ./tensorflow/tensorflow/core/framework/collective.su ./tensorflow/tensorflow/core/framework/common_shape_fns.cyclo ./tensorflow/tensorflow/core/framework/common_shape_fns.d ./tensorflow/tensorflow/core/framework/common_shape_fns.o ./tensorflow/tensorflow/core/framework/common_shape_fns.su ./tensorflow/tensorflow/core/framework/common_shape_fns_test.cyclo ./tensorflow/tensorflow/core/framework/common_shape_fns_test.d ./tensorflow/tensorflow/core/framework/common_shape_fns_test.o ./tensorflow/tensorflow/core/framework/common_shape_fns_test.su ./tensorflow/tensorflow/core/framework/dataset.cyclo ./tensorflow/tensorflow/core/framework/dataset.d ./tensorflow/tensorflow/core/framework/dataset.o ./tensorflow/tensorflow/core/framework/dataset.su ./tensorflow/tensorflow/core/framework/dataset_test.cyclo ./tensorflow/tensorflow/core/framework/dataset_test.d ./tensorflow/tensorflow/core/framework/dataset_test.o ./tensorflow/tensorflow/core/framework/dataset_test.su ./tensorflow/tensorflow/core/framework/device.cyclo ./tensorflow/tensorflow/core/framework/device.d ./tensorflow/tensorflow/core/framework/device.o ./tensorflow/tensorflow/core/framework/device.su ./tensorflow/tensorflow/core/framework/device_base.cyclo ./tensorflow/tensorflow/core/framework/device_base.d ./tensorflow/tensorflow/core/framework/device_base.o ./tensorflow/tensorflow/core/framework/device_base.su ./tensorflow/tensorflow/core/framework/device_base_test.cyclo ./tensorflow/tensorflow/core/framework/device_base_test.d ./tensorflow/tensorflow/core/framework/device_base_test.o ./tensorflow/tensorflow/core/framework/device_base_test.su ./tensorflow/tensorflow/core/framework/device_factory.cyclo ./tensorflow/tensorflow/core/framework/device_factory.d ./tensorflow/tensorflow/core/framework/device_factory.o ./tensorflow/tensorflow/core/framework/device_factory.su ./tensorflow/tensorflow/core/framework/disable_jit_test.cyclo ./tensorflow/tensorflow/core/framework/disable_jit_test.d ./tensorflow/tensorflow/core/framework/disable_jit_test.o ./tensorflow/tensorflow/core/framework/disable_jit_test.su ./tensorflow/tensorflow/core/framework/fake_input.cyclo ./tensorflow/tensorflow/core/framework/fake_input.d ./tensorflow/tensorflow/core/framework/fake_input.o ./tensorflow/tensorflow/core/framework/fake_input.su ./tensorflow/tensorflow/core/framework/full_type_inference_util.cyclo ./tensorflow/tensorflow/core/framework/full_type_inference_util.d ./tensorflow/tensorflow/core/framework/full_type_inference_util.o ./tensorflow/tensorflow/core/framework/full_type_inference_util.su ./tensorflow/tensorflow/core/framework/full_type_inference_util_test.cyclo ./tensorflow/tensorflow/core/framework/full_type_inference_util_test.d ./tensorflow/tensorflow/core/framework/full_type_inference_util_test.o ./tensorflow/tensorflow/core/framework/full_type_inference_util_test.su ./tensorflow/tensorflow/core/framework/full_type_util.cyclo ./tensorflow/tensorflow/core/framework/full_type_util.d ./tensorflow/tensorflow/core/framework/full_type_util.o ./tensorflow/tensorflow/core/framework/full_type_util.su ./tensorflow/tensorflow/core/framework/full_type_util_test.cyclo ./tensorflow/tensorflow/core/framework/full_type_util_test.d ./tensorflow/tensorflow/core/framework/full_type_util_test.o ./tensorflow/tensorflow/core/framework/full_type_util_test.su ./tensorflow/tensorflow/core/framework/function.cyclo ./tensorflow/tensorflow/core/framework/function.d ./tensorflow/tensorflow/core/framework/function.o ./tensorflow/tensorflow/core/framework/function.su ./tensorflow/tensorflow/core/framework/function_handle_cache.cyclo ./tensorflow/tensorflow/core/framework/function_handle_cache.d ./tensorflow/tensorflow/core/framework/function_handle_cache.o ./tensorflow/tensorflow/core/framework/function_handle_cache.su ./tensorflow/tensorflow/core/framework/function_test.cyclo ./tensorflow/tensorflow/core/framework/function_test.d ./tensorflow/tensorflow/core/framework/function_test.o ./tensorflow/tensorflow/core/framework/function_test.su ./tensorflow/tensorflow/core/framework/function_testlib.cyclo ./tensorflow/tensorflow/core/framework/function_testlib.d ./tensorflow/tensorflow/core/framework/function_testlib.o ./tensorflow/tensorflow/core/framework/function_testlib.su ./tensorflow/tensorflow/core/framework/graph_def_util.cyclo ./tensorflow/tensorflow/core/framework/graph_def_util.d ./tensorflow/tensorflow/core/framework/graph_def_util.o
	-$(RM) ./tensorflow/tensorflow/core/framework/graph_def_util.su ./tensorflow/tensorflow/core/framework/graph_def_util_test.cyclo ./tensorflow/tensorflow/core/framework/graph_def_util_test.d ./tensorflow/tensorflow/core/framework/graph_def_util_test.o ./tensorflow/tensorflow/core/framework/graph_def_util_test.su ./tensorflow/tensorflow/core/framework/graph_to_functiondef.cyclo ./tensorflow/tensorflow/core/framework/graph_to_functiondef.d ./tensorflow/tensorflow/core/framework/graph_to_functiondef.o ./tensorflow/tensorflow/core/framework/graph_to_functiondef.su ./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.cyclo ./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.d ./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.o ./tensorflow/tensorflow/core/framework/graph_to_functiondef_test.su ./tensorflow/tensorflow/core/framework/kernel_def_builder.cyclo ./tensorflow/tensorflow/core/framework/kernel_def_builder.d ./tensorflow/tensorflow/core/framework/kernel_def_builder.o ./tensorflow/tensorflow/core/framework/kernel_def_builder.su ./tensorflow/tensorflow/core/framework/kernel_def_builder_test.cyclo ./tensorflow/tensorflow/core/framework/kernel_def_builder_test.d ./tensorflow/tensorflow/core/framework/kernel_def_builder_test.o ./tensorflow/tensorflow/core/framework/kernel_def_builder_test.su ./tensorflow/tensorflow/core/framework/kernel_def_util.cyclo ./tensorflow/tensorflow/core/framework/kernel_def_util.d ./tensorflow/tensorflow/core/framework/kernel_def_util.o ./tensorflow/tensorflow/core/framework/kernel_def_util.su ./tensorflow/tensorflow/core/framework/kernel_def_util_test.cyclo ./tensorflow/tensorflow/core/framework/kernel_def_util_test.d ./tensorflow/tensorflow/core/framework/kernel_def_util_test.o ./tensorflow/tensorflow/core/framework/kernel_def_util_test.su ./tensorflow/tensorflow/core/framework/kernel_shape_util.cyclo ./tensorflow/tensorflow/core/framework/kernel_shape_util.d ./tensorflow/tensorflow/core/framework/kernel_shape_util.o ./tensorflow/tensorflow/core/framework/kernel_shape_util.su ./tensorflow/tensorflow/core/framework/load_library.cyclo ./tensorflow/tensorflow/core/framework/load_library.d ./tensorflow/tensorflow/core/framework/load_library.o ./tensorflow/tensorflow/core/framework/load_library.su ./tensorflow/tensorflow/core/framework/local_rendezvous.cyclo ./tensorflow/tensorflow/core/framework/local_rendezvous.d ./tensorflow/tensorflow/core/framework/local_rendezvous.o ./tensorflow/tensorflow/core/framework/local_rendezvous.su ./tensorflow/tensorflow/core/framework/log_memory.cyclo ./tensorflow/tensorflow/core/framework/log_memory.d ./tensorflow/tensorflow/core/framework/log_memory.o ./tensorflow/tensorflow/core/framework/log_memory.su ./tensorflow/tensorflow/core/framework/logging.cyclo ./tensorflow/tensorflow/core/framework/logging.d ./tensorflow/tensorflow/core/framework/logging.o ./tensorflow/tensorflow/core/framework/logging.su ./tensorflow/tensorflow/core/framework/lookup_interface.cyclo ./tensorflow/tensorflow/core/framework/lookup_interface.d ./tensorflow/tensorflow/core/framework/lookup_interface.o ./tensorflow/tensorflow/core/framework/lookup_interface.su ./tensorflow/tensorflow/core/framework/memory_types.cyclo ./tensorflow/tensorflow/core/framework/memory_types.d ./tensorflow/tensorflow/core/framework/memory_types.o ./tensorflow/tensorflow/core/framework/memory_types.su ./tensorflow/tensorflow/core/framework/memory_types_test.cyclo ./tensorflow/tensorflow/core/framework/memory_types_test.d ./tensorflow/tensorflow/core/framework/memory_types_test.o ./tensorflow/tensorflow/core/framework/memory_types_test.su ./tensorflow/tensorflow/core/framework/metrics.cyclo ./tensorflow/tensorflow/core/framework/metrics.d ./tensorflow/tensorflow/core/framework/metrics.o ./tensorflow/tensorflow/core/framework/metrics.su ./tensorflow/tensorflow/core/framework/model.cyclo ./tensorflow/tensorflow/core/framework/model.d ./tensorflow/tensorflow/core/framework/model.o ./tensorflow/tensorflow/core/framework/model.su ./tensorflow/tensorflow/core/framework/model_test.cyclo ./tensorflow/tensorflow/core/framework/model_test.d ./tensorflow/tensorflow/core/framework/model_test.o ./tensorflow/tensorflow/core/framework/model_test.su ./tensorflow/tensorflow/core/framework/node_def_builder.cyclo ./tensorflow/tensorflow/core/framework/node_def_builder.d ./tensorflow/tensorflow/core/framework/node_def_builder.o ./tensorflow/tensorflow/core/framework/node_def_builder.su ./tensorflow/tensorflow/core/framework/node_def_builder_test.cyclo ./tensorflow/tensorflow/core/framework/node_def_builder_test.d ./tensorflow/tensorflow/core/framework/node_def_builder_test.o ./tensorflow/tensorflow/core/framework/node_def_builder_test.su ./tensorflow/tensorflow/core/framework/node_def_util.cyclo ./tensorflow/tensorflow/core/framework/node_def_util.d ./tensorflow/tensorflow/core/framework/node_def_util.o ./tensorflow/tensorflow/core/framework/node_def_util.su ./tensorflow/tensorflow/core/framework/node_def_util_test.cyclo ./tensorflow/tensorflow/core/framework/node_def_util_test.d ./tensorflow/tensorflow/core/framework/node_def_util_test.o ./tensorflow/tensorflow/core/framework/node_def_util_test.su ./tensorflow/tensorflow/core/framework/node_properties.cyclo ./tensorflow/tensorflow/core/framework/node_properties.d ./tensorflow/tensorflow/core/framework/node_properties.o ./tensorflow/tensorflow/core/framework/node_properties.su ./tensorflow/tensorflow/core/framework/node_properties_test.cyclo ./tensorflow/tensorflow/core/framework/node_properties_test.d ./tensorflow/tensorflow/core/framework/node_properties_test.o ./tensorflow/tensorflow/core/framework/node_properties_test.su ./tensorflow/tensorflow/core/framework/op.cyclo ./tensorflow/tensorflow/core/framework/op.d ./tensorflow/tensorflow/core/framework/op.o ./tensorflow/tensorflow/core/framework/op.su ./tensorflow/tensorflow/core/framework/op_compatibility_test.cyclo
	-$(RM) ./tensorflow/tensorflow/core/framework/op_compatibility_test.d ./tensorflow/tensorflow/core/framework/op_compatibility_test.o ./tensorflow/tensorflow/core/framework/op_compatibility_test.su ./tensorflow/tensorflow/core/framework/op_def_builder.cyclo ./tensorflow/tensorflow/core/framework/op_def_builder.d ./tensorflow/tensorflow/core/framework/op_def_builder.o ./tensorflow/tensorflow/core/framework/op_def_builder.su ./tensorflow/tensorflow/core/framework/op_def_builder_test.cyclo ./tensorflow/tensorflow/core/framework/op_def_builder_test.d ./tensorflow/tensorflow/core/framework/op_def_builder_test.o ./tensorflow/tensorflow/core/framework/op_def_builder_test.su ./tensorflow/tensorflow/core/framework/op_def_util.cyclo ./tensorflow/tensorflow/core/framework/op_def_util.d ./tensorflow/tensorflow/core/framework/op_def_util.o ./tensorflow/tensorflow/core/framework/op_def_util.su ./tensorflow/tensorflow/core/framework/op_def_util_test.cyclo ./tensorflow/tensorflow/core/framework/op_def_util_test.d ./tensorflow/tensorflow/core/framework/op_def_util_test.o ./tensorflow/tensorflow/core/framework/op_def_util_test.su ./tensorflow/tensorflow/core/framework/op_gen_lib.cyclo ./tensorflow/tensorflow/core/framework/op_gen_lib.d ./tensorflow/tensorflow/core/framework/op_gen_lib.o ./tensorflow/tensorflow/core/framework/op_gen_lib.su ./tensorflow/tensorflow/core/framework/op_gen_lib_test.cyclo ./tensorflow/tensorflow/core/framework/op_gen_lib_test.d ./tensorflow/tensorflow/core/framework/op_gen_lib_test.o ./tensorflow/tensorflow/core/framework/op_gen_lib_test.su ./tensorflow/tensorflow/core/framework/op_kernel.cyclo ./tensorflow/tensorflow/core/framework/op_kernel.d ./tensorflow/tensorflow/core/framework/op_kernel.o ./tensorflow/tensorflow/core/framework/op_kernel.su ./tensorflow/tensorflow/core/framework/op_kernel_test.cyclo ./tensorflow/tensorflow/core/framework/op_kernel_test.d ./tensorflow/tensorflow/core/framework/op_kernel_test.o ./tensorflow/tensorflow/core/framework/op_kernel_test.su ./tensorflow/tensorflow/core/framework/op_registration_test.cyclo ./tensorflow/tensorflow/core/framework/op_registration_test.d ./tensorflow/tensorflow/core/framework/op_registration_test.o ./tensorflow/tensorflow/core/framework/op_registration_test.su ./tensorflow/tensorflow/core/framework/op_segment.cyclo ./tensorflow/tensorflow/core/framework/op_segment.d ./tensorflow/tensorflow/core/framework/op_segment.o ./tensorflow/tensorflow/core/framework/op_segment.su ./tensorflow/tensorflow/core/framework/op_segment_test.cyclo ./tensorflow/tensorflow/core/framework/op_segment_test.d ./tensorflow/tensorflow/core/framework/op_segment_test.o ./tensorflow/tensorflow/core/framework/op_segment_test.su ./tensorflow/tensorflow/core/framework/ops_util.cyclo ./tensorflow/tensorflow/core/framework/ops_util.d ./tensorflow/tensorflow/core/framework/ops_util.o ./tensorflow/tensorflow/core/framework/ops_util.su ./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.cyclo ./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.d ./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.o ./tensorflow/tensorflow/core/framework/partial_tensor_shape_test.su ./tensorflow/tensorflow/core/framework/reader_base.cyclo ./tensorflow/tensorflow/core/framework/reader_base.d ./tensorflow/tensorflow/core/framework/reader_base.o ./tensorflow/tensorflow/core/framework/reader_base.su ./tensorflow/tensorflow/core/framework/ref_var.cyclo ./tensorflow/tensorflow/core/framework/ref_var.d ./tensorflow/tensorflow/core/framework/ref_var.o ./tensorflow/tensorflow/core/framework/ref_var.su ./tensorflow/tensorflow/core/framework/rendezvous.cyclo ./tensorflow/tensorflow/core/framework/rendezvous.d ./tensorflow/tensorflow/core/framework/rendezvous.o ./tensorflow/tensorflow/core/framework/rendezvous.su ./tensorflow/tensorflow/core/framework/rendezvous_test.cyclo ./tensorflow/tensorflow/core/framework/rendezvous_test.d ./tensorflow/tensorflow/core/framework/rendezvous_test.o ./tensorflow/tensorflow/core/framework/rendezvous_test.su ./tensorflow/tensorflow/core/framework/resource_handle.cyclo ./tensorflow/tensorflow/core/framework/resource_handle.d ./tensorflow/tensorflow/core/framework/resource_handle.o ./tensorflow/tensorflow/core/framework/resource_handle.su ./tensorflow/tensorflow/core/framework/resource_handle_test.cyclo ./tensorflow/tensorflow/core/framework/resource_handle_test.d ./tensorflow/tensorflow/core/framework/resource_handle_test.o ./tensorflow/tensorflow/core/framework/resource_handle_test.su ./tensorflow/tensorflow/core/framework/resource_mgr.cyclo ./tensorflow/tensorflow/core/framework/resource_mgr.d ./tensorflow/tensorflow/core/framework/resource_mgr.o ./tensorflow/tensorflow/core/framework/resource_mgr.su ./tensorflow/tensorflow/core/framework/resource_mgr_test.cyclo ./tensorflow/tensorflow/core/framework/resource_mgr_test.d ./tensorflow/tensorflow/core/framework/resource_mgr_test.o ./tensorflow/tensorflow/core/framework/resource_mgr_test.su ./tensorflow/tensorflow/core/framework/resource_op_kernel_test.cyclo ./tensorflow/tensorflow/core/framework/resource_op_kernel_test.d ./tensorflow/tensorflow/core/framework/resource_op_kernel_test.o ./tensorflow/tensorflow/core/framework/resource_op_kernel_test.su ./tensorflow/tensorflow/core/framework/resource_var.cyclo ./tensorflow/tensorflow/core/framework/resource_var.d ./tensorflow/tensorflow/core/framework/resource_var.o ./tensorflow/tensorflow/core/framework/resource_var.su ./tensorflow/tensorflow/core/framework/resource_var_test.cyclo ./tensorflow/tensorflow/core/framework/resource_var_test.d ./tensorflow/tensorflow/core/framework/resource_var_test.o ./tensorflow/tensorflow/core/framework/resource_var_test.su ./tensorflow/tensorflow/core/framework/run_handler.cyclo ./tensorflow/tensorflow/core/framework/run_handler.d ./tensorflow/tensorflow/core/framework/run_handler.o ./tensorflow/tensorflow/core/framework/run_handler.su
	-$(RM) ./tensorflow/tensorflow/core/framework/run_handler_test.cyclo ./tensorflow/tensorflow/core/framework/run_handler_test.d ./tensorflow/tensorflow/core/framework/run_handler_test.o ./tensorflow/tensorflow/core/framework/run_handler_test.su ./tensorflow/tensorflow/core/framework/run_handler_util.cyclo ./tensorflow/tensorflow/core/framework/run_handler_util.d ./tensorflow/tensorflow/core/framework/run_handler_util.o ./tensorflow/tensorflow/core/framework/run_handler_util.su ./tensorflow/tensorflow/core/framework/run_handler_util_test.cyclo ./tensorflow/tensorflow/core/framework/run_handler_util_test.d ./tensorflow/tensorflow/core/framework/run_handler_util_test.o ./tensorflow/tensorflow/core/framework/run_handler_util_test.su ./tensorflow/tensorflow/core/framework/shape_inference.cyclo ./tensorflow/tensorflow/core/framework/shape_inference.d ./tensorflow/tensorflow/core/framework/shape_inference.o ./tensorflow/tensorflow/core/framework/shape_inference.su ./tensorflow/tensorflow/core/framework/shape_inference_test.cyclo ./tensorflow/tensorflow/core/framework/shape_inference_test.d ./tensorflow/tensorflow/core/framework/shape_inference_test.o ./tensorflow/tensorflow/core/framework/shape_inference_test.su ./tensorflow/tensorflow/core/framework/shape_inference_testutil.cyclo ./tensorflow/tensorflow/core/framework/shape_inference_testutil.d ./tensorflow/tensorflow/core/framework/shape_inference_testutil.o ./tensorflow/tensorflow/core/framework/shape_inference_testutil.su ./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.cyclo ./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.d ./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.o ./tensorflow/tensorflow/core/framework/shape_inference_testutil_test.su ./tensorflow/tensorflow/core/framework/tensor.cyclo ./tensorflow/tensorflow/core/framework/tensor.d ./tensorflow/tensorflow/core/framework/tensor.o ./tensorflow/tensorflow/core/framework/tensor.su ./tensorflow/tensorflow/core/framework/tensor_fuzz.cyclo ./tensorflow/tensorflow/core/framework/tensor_fuzz.d ./tensorflow/tensorflow/core/framework/tensor_fuzz.o ./tensorflow/tensorflow/core/framework/tensor_fuzz.su ./tensorflow/tensorflow/core/framework/tensor_shape.cyclo ./tensorflow/tensorflow/core/framework/tensor_shape.d ./tensorflow/tensorflow/core/framework/tensor_shape.o ./tensorflow/tensorflow/core/framework/tensor_shape.su ./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.cyclo ./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.d ./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.o ./tensorflow/tensorflow/core/framework/tensor_shape_fuzz.su ./tensorflow/tensorflow/core/framework/tensor_shape_test.cyclo ./tensorflow/tensorflow/core/framework/tensor_shape_test.d ./tensorflow/tensorflow/core/framework/tensor_shape_test.o ./tensorflow/tensorflow/core/framework/tensor_shape_test.su ./tensorflow/tensorflow/core/framework/tensor_slice.cyclo ./tensorflow/tensorflow/core/framework/tensor_slice.d ./tensorflow/tensorflow/core/framework/tensor_slice.o ./tensorflow/tensorflow/core/framework/tensor_slice.su ./tensorflow/tensorflow/core/framework/tensor_slice_test.cyclo ./tensorflow/tensorflow/core/framework/tensor_slice_test.d ./tensorflow/tensorflow/core/framework/tensor_slice_test.o ./tensorflow/tensorflow/core/framework/tensor_slice_test.su ./tensorflow/tensorflow/core/framework/tensor_test.cyclo ./tensorflow/tensorflow/core/framework/tensor_test.d ./tensorflow/tensorflow/core/framework/tensor_test.o ./tensorflow/tensorflow/core/framework/tensor_test.su ./tensorflow/tensorflow/core/framework/tensor_testutil.cyclo ./tensorflow/tensorflow/core/framework/tensor_testutil.d ./tensorflow/tensorflow/core/framework/tensor_testutil.o ./tensorflow/tensorflow/core/framework/tensor_testutil.su ./tensorflow/tensorflow/core/framework/tensor_testutil_test.cyclo ./tensorflow/tensorflow/core/framework/tensor_testutil_test.d ./tensorflow/tensorflow/core/framework/tensor_testutil_test.o ./tensorflow/tensorflow/core/framework/tensor_testutil_test.su ./tensorflow/tensorflow/core/framework/tensor_util.cyclo ./tensorflow/tensorflow/core/framework/tensor_util.d ./tensorflow/tensorflow/core/framework/tensor_util.o ./tensorflow/tensorflow/core/framework/tensor_util.su ./tensorflow/tensorflow/core/framework/tensor_util_test.cyclo ./tensorflow/tensorflow/core/framework/tensor_util_test.d ./tensorflow/tensorflow/core/framework/tensor_util_test.o ./tensorflow/tensorflow/core/framework/tensor_util_test.su ./tensorflow/tensorflow/core/framework/tracking_allocator_test.cyclo ./tensorflow/tensorflow/core/framework/tracking_allocator_test.d ./tensorflow/tensorflow/core/framework/tracking_allocator_test.o ./tensorflow/tensorflow/core/framework/tracking_allocator_test.su ./tensorflow/tensorflow/core/framework/typed_allocator.cyclo ./tensorflow/tensorflow/core/framework/typed_allocator.d ./tensorflow/tensorflow/core/framework/typed_allocator.o ./tensorflow/tensorflow/core/framework/typed_allocator.su ./tensorflow/tensorflow/core/framework/types.cyclo ./tensorflow/tensorflow/core/framework/types.d ./tensorflow/tensorflow/core/framework/types.o ./tensorflow/tensorflow/core/framework/types.su ./tensorflow/tensorflow/core/framework/types_test.cyclo ./tensorflow/tensorflow/core/framework/types_test.d ./tensorflow/tensorflow/core/framework/types_test.o ./tensorflow/tensorflow/core/framework/types_test.su ./tensorflow/tensorflow/core/framework/variant.cyclo ./tensorflow/tensorflow/core/framework/variant.d ./tensorflow/tensorflow/core/framework/variant.o ./tensorflow/tensorflow/core/framework/variant.su ./tensorflow/tensorflow/core/framework/variant_op_copy_test.cyclo ./tensorflow/tensorflow/core/framework/variant_op_copy_test.d ./tensorflow/tensorflow/core/framework/variant_op_copy_test.o ./tensorflow/tensorflow/core/framework/variant_op_copy_test.su ./tensorflow/tensorflow/core/framework/variant_op_registry.cyclo
	-$(RM) ./tensorflow/tensorflow/core/framework/variant_op_registry.d ./tensorflow/tensorflow/core/framework/variant_op_registry.o ./tensorflow/tensorflow/core/framework/variant_op_registry.su ./tensorflow/tensorflow/core/framework/variant_op_registry_test.cyclo ./tensorflow/tensorflow/core/framework/variant_op_registry_test.d ./tensorflow/tensorflow/core/framework/variant_op_registry_test.o ./tensorflow/tensorflow/core/framework/variant_op_registry_test.su ./tensorflow/tensorflow/core/framework/variant_tensor_data.cyclo ./tensorflow/tensorflow/core/framework/variant_tensor_data.d ./tensorflow/tensorflow/core/framework/variant_tensor_data.o ./tensorflow/tensorflow/core/framework/variant_tensor_data.su ./tensorflow/tensorflow/core/framework/variant_test.cyclo ./tensorflow/tensorflow/core/framework/variant_test.d ./tensorflow/tensorflow/core/framework/variant_test.o ./tensorflow/tensorflow/core/framework/variant_test.su ./tensorflow/tensorflow/core/framework/versions.cyclo ./tensorflow/tensorflow/core/framework/versions.d ./tensorflow/tensorflow/core/framework/versions.o ./tensorflow/tensorflow/core/framework/versions.su

.PHONY: clean-tensorflow-2f-tensorflow-2f-core-2f-framework

